stages:
  - build
  - test

image: ghcr.io/graalvm/graalvm-ce:21.0.4

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTIONS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true
  URL: "$DB_URL"
  USERNAME: "$DB_USERNAME"
  PASSWORD: "$DB_PASSWORD"

before_script:
  - apt-get update && apt-get install -y maven
  - mvn -v
  - java --version

cache:
  paths:
    - .m2/repository

build-job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths: 
      - target/*.jar

run_unit_tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    



