stages:
  - build

default:
  image: ubuntu:22.04

variables:
  MAVEN_CLI_OPTIONS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true
  URL: "$DB_URL"
  USERNAME: "$DB_USERNAME"
  PASSWORD: "$DB_PASSWORD"

services:
  - name: mysql:9.0.0
    alias: sd3db
    variables:
      MYSQL_DATABASE: sd3
      MYSQL_ROOT_PASSWORD: $PASSWORD

build-job:
  stage: build
  script:
    - echo "Building project..."
    - apt-get update
    - apt-get install -y openjdk-21-jdk
    - chmod +x mvnw
    - ./mvnw clean compile package -DskipTests
  artifacts:
    paths:
      - target/


