stages: 
  - build
  - test
  - maven

default:
  image: ubuntu-latest

on: 
  pull_request:
    branches:
      - develop
      - main

build_app:
  stage: build
  script:
    - mvn clean install


run_unit_tests:
  stage: test
  script:
    - mvn test


verify_maven:
  stage: maven
  script:
    - mvn -v
