version: "3"
services:
  users-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      URL: jdbc:mysql://mysqldb:3306/sd3db?createDatabaseIfNotExist=true&serverTimezone=UTC
      USERNAME: root
      PASSWORD: sd5
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:9.0.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sd5
      MYSQL_PASSWORD: sd5
      MYSQL_DATABASE: sd3db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
